### PR TITLE
Switch to EdDSA for JWTs in tests

### PR DESCRIPTION
**Pull request by fstagni**

### CODE REVIEW

**Comment by chaen** [comment]
This tremendously slows down the tests, that's why it's so low. What library requires 1024 ?

**Comment by martynia** [comment]
See issue #278.
 J

**Comment by fstagni** [comment]
I'd merge this for now and look for better solution later on. @chaen @chrisburr ?

**Comment by chaen** [comment]
you have the same fixes in https://github.com/DIRACGrid/diracx/pull/281  that we commented on

**Comment by fstagni** [comment]
> you have the same fixes in #281 that we commented on

You mean this? https://github.com/DIRACGrid/diracx/pull/281#discussion_r1728853076 

I am waiting for a reply.

**Comment by chrisburr** [comment]
And https://github.com/DIRACGrid/diracx/pull/281#discussion_r1728853721
And https://github.com/DIRACGrid/diracx/pull/281#discussion_r1729005018

**Pull request merged**
